server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: goods
mybatis-plus:
  type-aliases-package: pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
    #账号密码添加在http://后面@与ip隔开
      defaultZone: http://root:a5613305@127.0.0.1:8003/eureka/
  instance:
    prefer-ip-address: true #使用ip在服务中显示状态

